@WebAPI_HostAddress = https://localhost:7076


POST {{WebAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "alexanderderevkov@yandex.ru",
  "password": "Alex123456",
  "confirmPassword": "Alex123456",
  "name": "Alex",
  "lastName": "Derevkov"
}

###


@id=11
GET {{WebAPI_HostAddress}}/api/users/{{id}}

###

@id=11
PUT {{WebAPI_HostAddress}}/api/users/{{id}}
Content-Type: application/json  

{
  "email":"dfqwedfweq@yandex.ru",
  "name":"fvwerfg",
  "lastName":"gqwer",
  "phone":null
}

###

GET {{WebAPI_HostAddress}}/api/users

###


GET {{WebAPI_HostAddress}}/api/chefs

###

@id=18
GET {{WebAPI_HostAddress}}/api/chefs/{{id}}

###



POST {{WebAPI_HostAddress}}/api/dishes
Content-Type: application/json

{
  "userId": 18,
  "name": "Super Dish", 
  "description": "Super Dish Desc",
  "category": "Super Dish Cat",
  "price": 1000,
  "currency": "RUB",
  "kitchen": "Russian"
}

###

GET {{WebAPI_HostAddress}}/api/dishes

###
