@WebAPI_HostAddress = https://localhost:7076


POST {{WebAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "alexanderderevkov@yandex.ru",
  "password": "Alex123456",
  "confirmPassword": "Alex123456",
  "name": "Alex",
  "lastName": "Derevkov"
}

###


@id=11
GET {{WebAPI_HostAddress}}/api/users/{{id}}

###

@id=11
PUT {{WebAPI_HostAddress}}/api/users/{{id}}
Content-Type: application/json

{
  "email":"dfqwedfweq@yandex.ru",
  "name":"fvwerfg",
  "lastName":"gqwer",
  "phone":null
}

###

GET {{WebAPI_HostAddress}}/api/users

###

