using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WebAPI.Migrations
{
    /// <inheritdoc />
    public partial class SeedInitialIngredients : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var ingredients = new (string value, string name, string category)[]
{
    // ========== ОВОЩИ ==========
    ("tomato", "Помидоры", "овощи"),
    ("cucumber", "Огурцы", "овощи"),
    ("potato", "Картофель", "овощи"),
    ("carrot", "Морковь", "овощи"),
    ("onion", "Лук репчатый", "овощи"),
    ("garlic", "Чеснок", "овощи"),
    ("bell_pepper", "Перец болгарский", "овощи"),
    ("cabbage", "Капуста белокочанная", "овощи"),
    ("cauliflower", "Цветная капуста", "овощи"),
    ("broccoli", "Брокколи", "овощи"),
    ("zucchini", "Кабачки", "овощи"),
    ("eggplant", "Баклажаны", "овощи"),
    ("pumpkin", "Тыква", "овощи"),
    ("squash", "Патиссоны", "овощи"),
    ("radish", "Редис", "овощи"),
    ("daikon", "Дайкон", "овощи"),
    ("beetroot", "Свёкла", "овощи"),
    ("celery_root", "Корень сельдерея", "овощи"),
    ("parsnip", "Пастернак", "овощи"),
    ("turnip", "Репа", "овощи"),
    ("horseradish", "Хрен", "овощи"),
    ("sweet_potato", "Батат", "овощи"),
    ("artichoke", "Артишок", "овощи"),
    ("asparagus", "Спаржа", "овощи"),
    ("green_beans", "Стручковая фасоль", "овощи"),
    ("peas", "Горошек", "овощи"),
    ("corn", "Кукуруза", "овощи"),
    ("spinach", "Шпинат", "зелень"),
    ("arugula", "Руккола", "зелень"),
    ("lettuce", "Салат листовой", "зелень"),
    ("iceberg", "Айсберг", "зелень"),
    ("romano", "Романо", "зелень"),
    ("chard", "Мангольд", "зелень"),
    ("sorrel", "Щавель", "зелень"),
    ("dill", "Укроп", "зелень"),
    ("parsley", "Петрушка", "зелень"),
    ("cilantro", "Кинза", "зелень"),
    ("basil", "Базилик", "зелень"),
    ("mint", "Мята", "зелень"),
    ("rosemary", "Розмарин", "зелень"),
    ("thyme", "Тимьян", "зелень"),
    ("oregano", "Орегано", "зелень"),
    ("sage", "Шалфей", "зелень"),
    ("tarragon", "Эстрагон", "зелень"),
    ("bay_leaf", "Лавровый лист", "специи"),
    ("green_onion", "Зелёный лук", "зелень"),
    ("leek", "Лук-порей", "овощи"),
    ("shallot", "Лук-шалот", "овощи"),
    ("chili_pepper", "Перец чили", "овощи"),
    ("jalapeno", "Халапеньо", "овощи"),
    ("habanero", "Хабанеро", "овощи"),
    ("ginger", "Имбирь", "специи"),
    ("turmeric", "Куркума", "специи"),
    ("lemongrass", "Лемонграсс", "специи"),

    // ========== ГРИБЫ ==========
    ("mushroom", "Шампиньоны", "грибы"),
    ("porcini", "Белые грибы", "грибы"),
    ("chanterelle", "Лисички", "грибы"),
    ("shiitake", "Шиитаке", "грибы"),
    ("oyster_mushroom", "Вешенки", "грибы"),
    ("truffle", "Трюфель", "грибы"),

    // ========== ФРУКТЫ И ЯГОДЫ ==========
    ("apple", "Яблоки", "фрукты"),
    ("pear", "Груши", "фрукты"),
    ("banana", "Бананы", "фрукты"),
    ("orange", "Апельсины", "фрукты"),
    ("mandarin", "Мандарины", "фрукты"),
    ("lemon", "Лимоны", "фрукты"),
    ("lime", "Лайм", "фрукты"),
    ("grapefruit", "Грейпфрут", "фрукты"),
    ("pineapple", "Ананас", "фрукты"),
    ("mango", "Манго", "фрукты"),
    ("avocado", "Авокадо", "фрукты"),
    ("strawberry", "Клубника", "ягоды"),
    ("raspberry", "Малина", "ягоды"),
    ("blueberry", "Голубика", "ягоды"),
    ("blackberry", "Ежевика", "ягоды"),
    ("cherry", "Вишня", "фрукты"),
    ("sweet_cherry", "Черешня", "фрукты"),
    ("plum", "Слива", "фрукты"),
    ("peach", "Персик", "фрукты"),
    ("nectarine", "Нектарин", "фрукты"),
    ("apricot", "Абрикос", "фрукты"),
    ("watermelon", "Арбуз", "фрукты"),
    ("melon", "Дыня", "фрукты"),
    ("grape", "Виноград", "фрукты"),
    ("cranberry", "Клюква", "ягоды"),
    ("currant", "Смородина", "ягоды"),
    ("gooseberry", "Крыжовник", "ягоды"),
    ("fig", "Инжир", "фрукты"),
    ("pomegranate", "Гранат", "фрукты"),
    ("kiwi", "Киви", "фрукты"),
    ("papaya", "Папайя", "фрукты"),
    ("coconut", "Кокос", "фрукты"),
    ("date", "Финики", "сухофрукты"),
    ("prune", "Чернослив", "сухофрукты"),
    ("raisin", "Изюм", "сухофрукты"),
    ("dried_apricot", "Курага", "сухофрукты"),

    // ========== МЯСО, ПТИЦА, СУБПРОДУКТЫ ==========
    ("beef", "Говядина", "мясо"),
    ("veal", "Телятина", "мясо"),
    ("pork", "Свинина", "мясо"),
    ("lamb", "Баранина", "мясо"),
    ("rabbit", "Кролик", "мясо"),
    ("chicken", "Курица", "птица"),
    ("turkey", "Индейка", "птица"),
    ("duck", "Утка", "птица"),
    ("goose", "Гусь", "птица"),
    ("quail", "Перепелка", "птица"),
    ("sausage", "Колбаса", "колбасные изделия"),
    ("bacon", "Бекон", "колбасные изделия"),
    ("ham", "Ветчина", "колбасные изделия"),
    ("salami", "Салями", "колбасные изделия"),
    ("minced_meat", "Фарш", "мясо"),
    ("beef_liver", "Говяжья печень", "субпродукты"),
    ("chicken_liver", "Куриная печень", "субпродукты"),
    ("beef_tongue", "Говяжий язык", "субпродукты"),
    ("heart", "Сердце", "субпродукты"),
    ("kidney", "Почки", "субпродукты"),

    // ========== РЫБА ==========
    ("fish", "Рыба", "рыба"),
    ("salmon", "Лосось", "рыба"),
    ("trout", "Форель", "рыба"),
    ("tuna", "Тунец", "рыба"),
    ("cod", "Треска", "рыба"),
    ("pollock", "Минтай", "рыба"),
    ("haddock", "Пикша", "рыба"),
    ("halibut", "Палтус", "рыба"),
    ("flounder", "Камбала", "рыба"),
    ("mackerel", "Скумбрия", "рыба"),
    ("herring", "Сельдь", "рыба"),
    ("sardine", "Сардина", "рыба"),
    ("perch", "Окунь", "рыба"),
    ("pike", "Щука", "рыба"),
    ("carp", "Карп", "рыба"),
    ("catfish", "Сом", "рыба"),
    ("redfish", "Красная рыба", "рыба"),

    // ========== МОРЕПРОДУКТЫ ==========
    ("seafood", "Морепродукты", "морепродукты"),
    ("shrimp", "Креветки", "морепродукты"),
    ("prawn", "Королевские креветки", "морепродукты"),
    ("mussels", "Мидии", "морепродукты"),
    ("squid", "Кальмары", "морепродукты"),
    ("octopus", "Осьминог", "морепродукты"),
    ("scallops", "Морские гребешки", "морепродукты"),
    ("oysters", "Устрицы", "морепродукты"),
    ("crabs", "Крабы", "морепродукты"),
    ("lobster", "Омар", "морепродукты"),
    ("crayfish", "Раки", "морепродукты"),
    ("sea_cocktail", "Морской коктейль", "морепродукты"),

    // ========== МОЛОЧНЫЕ ПРОДУКТЫ, ЯЙЦА ==========
    ("milk", "Молоко", "молочные продукты"),
    ("cream", "Сливки", "молочные продукты"),
    ("butter", "Сливочное масло", "молочные продукты"),
    ("cheese", "Сыр", "молочные продукты"),
    ("parmesan", "Пармезан", "молочные продукты"),
    ("mozzarella", "Моцарелла", "молочные продукты"),
    ("cheddar", "Чеддер", "молочные продукты"),
    ("gouda", "Гауда", "молочные продукты"),
    ("brie", "Бри", "молочные продукты"),
    ("camembert", "Камамбер", "молочные продукты"),
    ("feta", "Фета", "молочные продукты"),
    ("ricotta", "Рикотта", "молочные продукты"),
    ("cottage_cheese", "Творог", "молочные продукты"),
    ("sour_cream", "Сметана", "молочные продукты"),
    ("yogurt", "Йогурт", "молочные продукты"),
    ("kefir", "Кефир", "молочные продукты"),
    ("condensed_milk", "Сгущённое молоко", "молочные продукты"),
    ("ice_cream", "Мороженое", "десерты"),
    ("egg", "Яйца", "яйца"),
    ("quail_egg", "Перепелиные яйца", "яйца"),

    // ========== МУКА, КРУПЫ, МАКАРОНЫ ==========
    ("flour", "Мука", "мука и крупы"),
    ("wheat_flour", "Пшеничная мука", "мука и крупы"),
    ("rye_flour", "Ржаная мука", "мука и крупы"),
    ("corn_flour", "Кукурузная мука", "мука и крупы"),
    ("rice_flour", "Рисовая мука", "мука и крупы"),
    ("buckwheat_flour", "Гречневая мука", "мука и крупы"),
    ("almond_flour", "Миндальная мука", "мука и крупы"),
    ("coconut_flour", "Кокосовая мука", "мука и крупы"),
    ("breadcrumbs", "Панировочные сухари", "панировка"),
    ("pasta", "Макароны", "макаронные изделия"),
    ("spaghetti", "Спагетти", "макаронные изделия"),
    ("penne", "Пенне", "макаронные изделия"),
    ("fettuccine", "Феттуччине", "макаронные изделия"),
    ("lasagna_sheets", "Листы лазаньи", "макаронные изделия"),
    ("rice", "Рис", "крупы"),
    ("white_rice", "Белый рис", "крупы"),
    ("brown_rice", "Бурый рис", "крупы"),
    ("wild_rice", "Дикий рис", "крупы"),
    ("basmati_rice", "Рис басмати", "крупы"),
    ("jasmine_rice", "Рис жасмин", "крупы"),
    ("arborio_rice", "Рис арборио", "крупы"),
    ("buckwheat", "Гречка", "крупы"),
    ("oatmeal", "Овсяные хлопья", "крупы"),
    ("semolina", "Манка", "крупы"),
    ("pearl_barley", "Перловка", "крупы"),
    ("barley_groats", "Ячневая крупа", "крупы"),
    ("couscous", "Кускус", "крупы"),
    ("bulgur", "Булгур", "крупы"),
    ("quinoa", "Киноа", "крупы"),
    ("millet", "Пшено", "крупы"),
    ("polenta", "Полента", "крупы"),

    // ========== БОБОВЫЕ ==========
    ("beans", "Фасоль", "бобовые"),
    ("red_beans", "Красная фасоль", "бобовые"),
    ("white_beans", "Белая фасоль", "бобовые"),
    ("black_beans", "Чёрная фасоль", "бобовые"),
    ("lentils", "Чечевица", "бобовые"),
    ("chickpeas", "Нут", "бобовые"),
    ("soybeans", "Соя", "бобовые"),
    ("tofu", "Тофу", "бобовые"),
    ("tempeh", "Темпе", "бобовые"),
    ("edamame", "Эдамаме", "бобовые"),

    // ========== ОРЕХИ И СЕМЕНА ==========
    ("nuts", "Орехи", "орехи"),
    ("walnuts", "Грецкие орехи", "орехи"),
    ("almonds", "Миндаль", "орехи"),
    ("hazelnuts", "Фундук", "орехи"),
    ("cashews", "Кешью", "орехи"),
    ("pistachios", "Фисташки", "орехи"),
    ("pecans", "Пекан", "орехи"),
    ("brazil_nut", "Бразильский орех", "орехи"),
    ("macadamia", "Макадамия", "орехи"),
    ("peanuts", "Арахис", "орехи"),
    ("pine_nuts", "Кедровые орехи", "орехи"),
    ("coconut_chips", "Кокосовая стружка", "орехи"),
    ("sesame", "Кунжут", "семена"),
    ("poppy_seed", "Мак", "семена"),
    ("flax_seed", "Льняное семя", "семена"),
    ("chia_seed", "Семена чиа", "семена"),
    ("sunflower_seed", "Семечки подсолнуха", "семена"),
    ("pumpkin_seed", "Тыквенные семечки", "семена"),

    // ========== МАСЛА И ЖИРЫ ==========
    ("vegetable_oil", "Растительное масло", "масла"),
    ("olive_oil", "Оливковое масло", "масла"),
    ("sunflower_oil", "Подсолнечное масло", "масла"),
    ("corn_oil", "Кукурузное масло", "масла"),
    ("rapeseed_oil", "Рапсовое масло", "масла"),
    ("sesame_oil", "Кунжутное масло", "масла"),
    ("coconut_oil", "Кокосовое масло", "масла"),
    ("linseed_oil", "Льняное масло", "масла"),
    ("avocado_oil", "Масло авокадо", "масла"),
    ("walnut_oil", "Ореховое масло", "масла"),
    ("butter_ghee", "Топлёное масло", "масла"),

    // ========== СПЕЦИИ, САХАР, ПРИПРАВЫ ==========
    ("salt", "Соль", "специи"),
    ("sea_salt", "Морская соль", "специи"),
    ("black_pepper", "Чёрный перец", "специи"),
    ("white_pepper", "Белый перец", "специи"),
    ("red_pepper", "Красный перец", "специи"),
    ("allspice", "Душистый перец", "специи"),
    ("paprika", "Паприка", "специи"),
    ("cayenne", "Кайенский перец", "специи"),
    ("cinnamon", "Корица", "специи"),
    ("clove", "Гвоздика", "специи"),
    ("nutmeg", "Мускатный орех", "специи"),
    ("cardamom", "Кардамон", "специи"),
    ("cumin", "Кумин (зира)", "специи"),
    ("coriander", "Кориандр", "специи"),
    ("turmeric", "Куркума", "специи"),
    ("saffron", "Шафран", "специи"),
    ("vanilla", "Ваниль", "специи"),
    ("vanilla_sugar", "Ванильный сахар", "специи"),
    ("star_anise", "Бадьян", "специи"),
    ("anise", "Анис", "специи"),
    ("fennel", "Фенхель", "специи"),
    ("caraway", "Тмин", "специи"),
    ("mustard_seed", "Горчичное зерно", "специи"),
    ("mustard", "Горчица", "соусы"),
    ("wasabi", "Васаби", "соусы"),
    ("horseradish_sauce", "Хрен", "соусы"),
    ("sugar", "Сахар", "сахар"),
    ("brown_sugar", "Коричневый сахар", "сахар"),
    ("powdered_sugar", "Сахарная пудра", "сахар"),
    ("honey", "Мёд", "сладости"),
    ("maple_syrup", "Кленовый сироп", "сладости"),
    ("chocolate", "Шоколад", "сладости"),
    ("cocoa", "Какао", "сладости"),
    ("jam", "Варенье", "сладости"),
    ("preserves", "Джем", "сладости"),
    ("marmalade", "Мармелад", "сладости"),

    // ========== СОУСЫ И ЗАПРАВКИ ==========
    ("mayonnaise", "Майонез", "соусы"),
    ("ketchup", "Кетчуп", "соусы"),
    ("soy_sauce", "Соевый соус", "соусы"),
    ("teriyaki", "Терияки", "соусы"),
    ("oyster_sauce", "Устричный соус", "соусы"),
    ("fish_sauce", "Рыбный соус", "соусы"),
    ("worcestershire_sauce", "Вустерширский соус", "соусы"),
    ("tabasco", "Табаско", "соусы"),
    ("sriracha", "Шрирача", "соусы"),
    ("bbq_sauce", "Барбекю соус", "соусы"),
    ("tomato_paste", "Томатная паста", "соусы"),
    ("tomato_sauce", "Томатный соус", "соусы"),
    ("pesto", "Песто", "соусы"),
    ("balsamic", "Бальзамический уксус", "уксус"),
    ("vinegar", "Уксус", "уксус"),
    ("apple_cider_vinegar", "Яблочный уксус", "уксус"),
    ("wine_vinegar", "Винный уксус", "уксус"),
    ("rice_vinegar", "Рисовый уксус", "уксус"),
    ("lemon_juice", "Лимонный сок", "соки"),
    ("lime_juice", "Сок лайма", "соки"),

    // ========== РАЗРЫХЛИТЕЛИ, ЗАГУСТИТЕЛИ ==========
    ("yeast", "Дрожжи", "разрыхлители"),
    ("baking_powder", "Разрыхлитель", "разрыхлители"),
    ("baking_soda", "Сода", "разрыхлители"),
    ("starch", "Крахмал", "загустители"),
    ("gelatin", "Желатин", "загустители"),
    ("agar_agar", "Агар-агар", "загустители"),

    // ========== БУЛЬОНЫ И ВОДА ==========
    ("water", "Вода", "вода"),
    ("broth", "Бульон", "бульоны"),
    ("chicken_broth", "Куриный бульон", "бульоны"),
    ("beef_broth", "Говяжий бульон", "бульоны"),
    ("vegetable_broth", "Овощной бульон", "бульоны"),
    ("fish_broth", "Рыбный бульон", "бульоны"),

    // ========== АЛКОГОЛЬ ==========
    ("wine", "Вино", "алкоголь"),
    ("red_wine", "Красное вино", "алкоголь"),
    ("white_wine", "Белое вино", "алкоголь"),
    ("vodka", "Водка", "алкоголь"),
    ("beer", "Пиво", "алкоголь"),
    ("cognac", "Коньяк", "алкоголь"),
    ("rum", "Ром", "алкоголь")
};

            foreach (var ing in ingredients)
            {
                migrationBuilder.InsertData(
                    table: "ingredients",
                    columns: new[] { "Name", "Value", "Category" },
                    values: new object[,] { { ing.name, ing.value, ing.category } }
                );
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            var values = new[]
            {
                "tomato", "cucumber", "potato", "carrot", "onion", "garlic", "bell_pepper", "cabbage",
                "cauliflower", "broccoli", "zucchini", "eggplant", "pumpkin", "squash", "radish", "daikon",
                "beetroot", "celery_root", "parsnip", "turnip", "horseradish", "sweet_potato", "artichoke",
                "asparagus", "green_beans", "peas", "corn", "spinach", "arugula", "lettuce", "iceberg",
                "romano", "chard", "sorrel", "dill", "parsley", "cilantro", "basil", "mint", "rosemary",
                "thyme", "oregano", "sage", "tarragon", "bay_leaf", "green_onion", "leek", "shallot",
                "chili_pepper", "jalapeno", "habanero", "ginger", "turmeric", "lemongrass", "mushroom",
                "porcini", "chanterelle", "shiitake", "oyster_mushroom", "truffle", "apple", "pear",
                "banana", "orange", "mandarin", "lemon", "lime", "grapefruit", "pineapple", "mango",
                "avocado", "strawberry", "raspberry", "blueberry", "blackberry", "cherry", "sweet_cherry",
                "plum", "peach", "nectarine", "apricot", "watermelon", "melon", "grape", "cranberry",
                "currant", "gooseberry", "fig", "pomegranate", "kiwi", "papaya", "coconut", "date",
                "prune", "raisin", "dried_apricot", "beef", "veal", "pork", "lamb", "rabbit", "chicken",
                "turkey", "duck", "goose", "quail", "sausage", "bacon", "ham", "salami", "minced_meat",
                "beef_liver", "chicken_liver", "beef_tongue", "heart", "kidney", "fish", "salmon", "trout",
                "tuna", "cod", "pollock", "haddock", "halibut", "flounder", "mackerel", "herring", "sardine",
                "perch", "pike", "carp", "catfish", "redfish", "seafood", "shrimp", "prawn", "mussels",
                "squid", "octopus", "scallops", "oysters", "crabs", "lobster", "crayfish", "sea_cocktail",
                "milk", "cream", "butter", "cheese", "parmesan", "mozzarella", "cheddar", "gouda", "brie",
                "camembert", "feta", "ricotta", "cottage_cheese", "sour_cream", "yogurt", "kefir",
                "condensed_milk", "ice_cream", "egg", "quail_egg", "flour", "wheat_flour", "rye_flour",
                "corn_flour", "rice_flour", "buckwheat_flour", "almond_flour", "coconut_flour", "breadcrumbs",
                "pasta", "spaghetti", "penne", "fettuccine", "lasagna_sheets", "rice", "white_rice",
                "brown_rice", "wild_rice", "basmati_rice", "jasmine_rice", "arborio_rice", "buckwheat",
                "oatmeal", "semolina", "pearl_barley", "barley_groats", "couscous", "bulgur", "quinoa",
                "millet", "polenta", "beans", "red_beans", "white_beans", "black_beans", "lentils",
                "chickpeas", "soybeans", "tofu", "tempeh", "edamame", "nuts", "walnuts", "almonds",
                "hazelnuts", "cashews", "pistachios", "pecans", "brazil_nut", "macadamia", "peanuts",
                "pine_nuts", "coconut_chips", "sesame", "poppy_seed", "flax_seed", "chia_seed",
                "sunflower_seed", "pumpkin_seed", "vegetable_oil", "olive_oil", "sunflower_oil", "corn_oil",
                "rapeseed_oil", "sesame_oil", "coconut_oil", "linseed_oil", "avocado_oil", "walnut_oil",
                "butter_ghee", "salt", "sea_salt", "black_pepper", "white_pepper", "red_pepper", "allspice",
                "paprika", "cayenne", "cinnamon", "clove", "nutmeg", "cardamom", "cumin", "coriander",
                "turmeric", "saffron", "vanilla", "vanilla_sugar", "star_anise", "anise", "fennel",
                "caraway", "mustard_seed", "mustard", "wasabi", "horseradish_sauce", "mayonnaise", "ketchup",
                "soy_sauce", "teriyaki", "oyster_sauce", "fish_sauce", "worcestershire_sauce", "tabasco",
                "sriracha", "bbq_sauce", "tomato_paste", "tomato_sauce", "pesto", "balsamic", "vinegar",
                "apple_cider_vinegar", "wine_vinegar", "rice_vinegar", "lemon_juice", "lime_juice", "sugar",
                "brown_sugar", "powdered_sugar", "honey", "maple_syrup", "chocolate", "cocoa", "jam",
                "preserves", "marmalade", "yeast", "baking_powder", "baking_soda", "starch", "gelatin",
                "agar_agar", "water", "broth", "chicken_broth", "beef_broth", "vegetable_broth",
                "fish_broth", "wine", "red_wine", "white_wine", "vodka", "beer", "cognac", "rum"
            };

            foreach (var value in values)
            {
                migrationBuilder.DeleteData(
                    table: "ingredients",
                    keyColumn: "value",
                    keyValue: value
                );
            }
        }
    }
}
